### PR TITLE
serial & rtc: some useful methods for working with the events object

### PR DESCRIPTION
**Pull request by lauralt**

### CODE REVIEW

**Review by alexandruag — COMMENTED** [review]
Looks good; just wondering if it sounds like a good idea to shorten both `rtc_evts` and `serial_evts` to `evts` (or `events`), since the serial and rtc parts are already implied by the containing type. No strong preference on my part here.

**Comment by andreeaflorescu** [comment]
> Looks good; just wondering if it sounds like a good idea to shorten both `rtc_evts` and `serial_evts` to `evts` (or `events`), since the serial and rtc parts are already implied by the containing type. No strong preference on my part here.

Sounds like a good idea to rename them to `events` as we should make use of the namespace in which their defined.

Otherwise, LGTM as well. I would add some more details to the commit message to why we are adding these methods (i.e. to make it possible to retrieve the events value in order to build the metrics system at the VMM level).

**Comment by lauralt** [comment]
Added a separate commit for renaming to `events`.

> Otherwise, LGTM as well. I would add some more details to the commit message to why we are adding these methods (i.e. to make it possible to retrieve the events value in order to build the metrics system at the VMM level).

Hmm, I find it more confusing than not saying anything at all, I would understand that this method is mandatory for building the metrics system (and it actually isn't). Why you are adding a method for retrieving a reference to something should be pretty self-explanatory though.

**Review by alexandruag — APPROVED** [review]

**Comment by andreeaflorescu** [comment]
> Hmm, I find it more confusing than not saying anything at all, I would understand that this method is mandatory for building the metrics system (and it actually isn't). Why you are adding a method for retrieving a reference to something should be pretty self-explanatory though.

It is actually unclear to me why you implement both Arc<T> where T: Events, and provide a method for retrieving the metrics. How are these supposed to be used, when should you use one and when the other?

**Review by andreeaflorescu — APPROVED** [review]

**Pull request merged**
